import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import openapiTS, { astToString } from "openapi-typescript"
import { openapi } from "../packages/contracts/src/openapi.ts"

async function main() {
  const here = dirname(fileURLToPath(import.meta.url))
  const root = resolve(here, "..")
  const check = process.argv.includes("--check")
  const local = process.argv.includes("--server-only")
  const spec = `${JSON.stringify(openapi, null, 2)}\n`
  const ast = await openapiTS(openapi)
  const endpoints = Object.keys(openapi.paths)
  const types = `// This file is generated by scripts/generate-contracts.ts. Do not edit.\n\n${astToString(ast)}`
  const client = `// This file is generated by scripts/generate-contracts.ts. Do not edit.\n\nimport type { paths } from "./market-api"\n\ntype Path = keyof paths\n\nexport const MARKET_ENDPOINTS = ${JSON.stringify(endpoints, null, 2)} as const satisfies readonly Path[]\n\nexport interface MarketClientOptions {\n  baseUrl: string\n  fetch?: typeof fetch\n  headers?: Record<string, string>\n}\n\nexport class MarketApiError extends Error {\n  constructor(\n    readonly status: number,\n    readonly payload: unknown,\n  ) {\n    super(\`Market API request failed with HTTP \${status}\`)\n    this.name = "MarketApiError"\n  }\n}\n\nexport class MarketClient {\n  private readonly base: string\n  private readonly fetcher: typeof fetch\n  private readonly headers: Record<string, string>\n\n  constructor(opts: MarketClientOptions) {\n    this.base = opts.baseUrl.replace(/\\/+$/, "")\n    this.fetcher = opts.fetch ?? fetch\n    this.headers = opts.headers ?? {}\n  }\n\n  async request<T>(path: Path, init: RequestInit = {}): Promise<T> {\n    const res = await this.fetcher(\`\${this.base}\${path}\`, {\n      ...init,\n      headers: { ...this.headers, ...init.headers },\n    })\n    const type = res.headers.get("content-type") ?? ""\n    const payload: unknown = type.includes("application/json") ? await res.json() : await res.text()\n    if (!res.ok) throw new MarketApiError(res.status, payload)\n    return payload as T\n  }\n}\n`
  const outputs = new Map([
    [resolve(root, "packages/contracts/openapi/market-v1.json"), spec],
    [resolve(root, "apps/web/src/generated/market-api.ts"), types],
    [resolve(root, "apps/web/src/generated/market-client.ts"), client],
    ...(!local
      ? ([
          [resolve(root, "../../packages/kilo-vscode/src/services/marketplace/generated/market-api.ts"), types],
          [resolve(root, "../../packages/kilo-vscode/src/services/marketplace/generated/market-client.ts"), client],
        ] as Array<[string, string]>)
      : []),
  ])
  const drift: string[] = []

  for (const [path, content] of outputs) {
    if (check) {
      const current = await readFile(path, "utf8").catch(() => "")
      if (current !== content) drift.push(path)
      continue
    }
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, content)
  }

  if (drift.length > 0) {
    console.error(`Generated contract artifacts are stale:\n${drift.join("\n")}`)
    process.exitCode = 1
    return
  }
  console.log(check ? "Generated contract artifacts are current." : `Generated ${outputs.size} contract artifacts.`)
}

void main()
