#!/usr/bin/env python3
"""Generate an installed VSIX runtime S1-S16 smoke execution request.

This helper produces an operator-facing request for the installed VS Code
runtime smoke that remains pending in the migration plan.  It does not execute
chat, does not install VSIX files, and does not decide M11 acceptance.
"""

from __future__ import annotations

import argparse
from pathlib import Path


CASES = [
    ("S1", "Native C QA call chain", "Ask about a C call chain in the target workspace.", "Native ChipMate code understanding/search tools only; no Word/Mermaid/artifact tools."),
    ("S2", "Macro/register QA", "Ask about a macro/register definition and its usage.", "Native code/search understanding path; no document-generation sidecar."),
    ("S3", "Document RAG QA", "Ask about an indexed existing document.", "Must expose/use `document_search`; no Word generation."),
    ("S4", "Artifact create/list", "Generate and list a report artifact.", "Expected `.chipmate/artifacts/.../artifact.json` and `declare_artifact`/artifact listing evidence."),
    ("S5", "Word create", "Create a small Word document from user-provided content.", "Generic Word creation only; no document runtime contract."),
    ("S6", "Word edit/add table", "Edit an existing Word document and add a table.", "New `.docx` artifact plus source backup or scoped edit evidence."),
    ("S7", "Word delete dry-run", "Dry-run deleting a section/table from a Word document.", "Dry-run impact first; apply only with explicit approval."),
    ("S8", "Word template", "Apply a representative company `.docx` template if available.", "Style inheritance or scoped warning; no placeholder/mail-merge contract promise."),
    ("S9", "Word merge/diff", "Merge or compare multiple Word documents.", "Bounded summary and artifact paths; image relationship preservation when applicable."),
    ("S10", "Word render", "Render Word to PDF/page PNG if renderer is configured.", "PDF/page PNG when renderer exists; otherwise warning diagnostics artifact."),
    ("S11", "Mermaid PNG", "Generate a Mermaid diagram and PNG.", "Expected `.mmd`, rendered PNG, and diagnostics artifact; no old missing-diagram repair."),
    ("S12", "Mermaid inserted into Word", "Insert a Mermaid figure into a Word artifact.", "New Word artifact with figure or scoped renderer warning."),
    ("S13", "Source-backed detail design", "Generate source-backed detail design for an embedded-C module.", "Skill-only migration; evidence, Markdown, diagrams, Word, and quality/limitation report."),
    ("S14", "Agent Terminal open", "Open Agent Terminal and analyze how to build the project.", "Default-off prompt or enabled terminal open evidence; no hidden command execution."),
    ("S15", "Agent Terminal dangerous command", "Ask for a dangerous command plan.", "Explicit confirmation required; no destructive command execution."),
    ("S16", "Qwen direct autocomplete", "Enable qwen-direct and trigger inline completion diagnostics.", "Read-only autocomplete smoke; protected source files must not be modified."),
]


FORBIDDEN_MARKERS = [
    "nextToolContract",
    "missingDeliverable",
    "validate_artifacts",
    "missing-required-artifact",
    "missing-mermaid-pngs",
    "建议先渲染缺失图表",
    "缺失文档合同规划",
]


def write_request(output: Path, target_profile: str, workspace_hint: str) -> None:
    lines = [
        "# Installed VSIX Runtime Smoke Request S1-S16",
        "",
        "- Status: `REQUEST_PENDING_INSTALLED_RUNTIME_EXECUTION`",
        f"- Target VS Code profile: `{target_profile}`",
        f"- Target workspace: `{workspace_hint}`",
        "- Scope: installed chat/runtime behavior, not extension-host command smoke",
        "",
        "## Preflight requirements",
        "",
        "- Install the current target VSIX with upgrade/force path.",
        "- Configure a working chat provider/model for runtime prompts.",
        "- Configure Document RAG embedding provider before S3 if S3 is in scope.",
        "- Use the target workspace/profile that should represent real user behavior.",
        "- Record raw chat/tool logs, output artifacts, and screenshots when UI behavior matters.",
        "",
        "## Cases",
        "",
        "| ID | Area | Prompt/request | Required boundary |",
        "|---|---|---|---|",
    ]
    for sid, area, prompt, boundary in CASES:
        lines.append(f"| {sid} | {area} | {prompt} | {boundary} |")

    lines.extend(
        [
            "",
            "## Required returned evidence",
            "",
            "- `runtime-smoke.tsv` with one row per attempted S-id and explicit status.",
            "- `runtime-intake-summary.md` generated by `docs/chipmate-feature-migration-runtime-smoke-intake-verify.py`.",
            "- Raw logs/transcripts proving actual tool sequence, not only final answers.",
            "- Artifact directories for S4-S13 where artifacts are expected.",
            "- Screenshots/logs for Agent Terminal visible UX in S14-S15.",
            "- S16 read-only guard evidence if source checkout evidence is used.",
            "",
            "## Runtime intake command",
            "",
            "```bash",
            "python3 docs/chipmate-feature-migration-runtime-smoke-intake-verify.py \\",
            "  --runtime-evidence <runtime-s1-s16-evidence-dir> \\",
            "  --output <runtime-intake-summary.md>",
            "```",
            "",
            "## Forbidden old ChipMate contract/repair markers",
            "",
        ]
    )
    lines.extend(f"- `{marker}`" for marker in FORBIDDEN_MARKERS)
    lines.extend(
        [
            "",
            "## Acceptance boundary",
            "",
            "This request is not acceptance evidence. S1-S16 remains incomplete until the installed runtime evidence is returned, runtime intake reports `PASS` for required cases, and M11 review accepts the evidence without native ChipMate regression.",
            "",
        ]
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target-profile", default="target VS Code profile")
    parser.add_argument("--workspace-hint", default="/path/to/target/workspace")
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    output = args.output_dir / "installed-runtime-smoke-s1-s16-request.md"
    write_request(output, args.target_profile, args.workspace_hint)
    print(f"WROTE: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
