import { Config } from "effect"
import { InstallationChannel } from "../installation/version" // chipmate_change

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

// chipmate_change start
function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

const UNSTABLE_CHANNELS = new Set(["dev", "beta", "local"])
function unstableDefault(key: string) {
  return truthy(key) || (!falsy(key) && UNSTABLE_CHANNELS.has(InstallationChannel))
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const CHIPMATE_EXPERIMENTAL = truthy("CHIPMATE_EXPERIMENTAL")
const CHIPMATE_DISABLE_CLAUDE_CODE = truthy("CHIPMATE_DISABLE_CLAUDE_CODE")
const CHIPMATE_DISABLE_CLAUDE_CODE_SKILLS = CHIPMATE_DISABLE_CLAUDE_CODE || truthy("CHIPMATE_DISABLE_CLAUDE_CODE_SKILLS")
// chipmate_change end
const copy = process.env["CHIPMATE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["CHIPMATE_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("CHIPMATE_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  CHIPMATE_AUTO_SHARE: truthy("CHIPMATE_AUTO_SHARE"), // chipmate_change
  CHIPMATE_AUTO_HEAP_SNAPSHOT: truthy("CHIPMATE_AUTO_HEAP_SNAPSHOT"),
  CHIPMATE_GIT_BASH_PATH: process.env["CHIPMATE_GIT_BASH_PATH"],
  CHIPMATE_CONFIG: process.env["CHIPMATE_CONFIG"],
  CHIPMATE_CONFIG_CONTENT: process.env["CHIPMATE_CONFIG_CONTENT"],
  CHIPMATE_DISABLE_AUTOUPDATE: truthy("CHIPMATE_DISABLE_AUTOUPDATE"),
  CHIPMATE_ALWAYS_NOTIFY_UPDATE: truthy("CHIPMATE_ALWAYS_NOTIFY_UPDATE"),
  CHIPMATE_DISABLE_PRUNE: truthy("CHIPMATE_DISABLE_PRUNE"),
  CHIPMATE_DISABLE_TERMINAL_TITLE: truthy("CHIPMATE_DISABLE_TERMINAL_TITLE"),
  CHIPMATE_SHOW_TTFD: truthy("CHIPMATE_SHOW_TTFD"),
  // chipmate_change start
  CHIPMATE_DISABLE_DEFAULT_PLUGINS: truthy("CHIPMATE_DISABLE_DEFAULT_PLUGINS"),
  CHIPMATE_DISABLE_LSP_DOWNLOAD: truthy("CHIPMATE_DISABLE_LSP_DOWNLOAD"),
  CHIPMATE_ENABLE_EXPERIMENTAL_MODELS: truthy("CHIPMATE_ENABLE_EXPERIMENTAL_MODELS"),
  // chipmate_change end
  CHIPMATE_DISABLE_AUTOCOMPACT: truthy("CHIPMATE_DISABLE_AUTOCOMPACT"),
  CHIPMATE_DISABLE_MODELS_FETCH: truthy("CHIPMATE_DISABLE_MODELS_FETCH"),
  CHIPMATE_DISABLE_MOUSE: truthy("CHIPMATE_DISABLE_MOUSE"),
  // chipmate_change start
  CHIPMATE_DISABLE_CLAUDE_CODE,
  CHIPMATE_DISABLE_CLAUDE_CODE_PROMPT: CHIPMATE_DISABLE_CLAUDE_CODE || truthy("CHIPMATE_DISABLE_CLAUDE_CODE_PROMPT"),
  CHIPMATE_DISABLE_CLAUDE_CODE_SKILLS,
  CHIPMATE_DISABLE_EXTERNAL_SKILLS: truthy("CHIPMATE_DISABLE_EXTERNAL_SKILLS"),
  CHIPMATE_EXPERIMENTAL_CUSTOMIZE_SKILL: unstableDefault("CHIPMATE_EXPERIMENTAL_CUSTOMIZE_SKILL"),
  // chipmate_change end
  CHIPMATE_FAKE_VCS: process.env["CHIPMATE_FAKE_VCS"],
  CHIPMATE_SERVER_PASSWORD: process.env["CHIPMATE_SERVER_PASSWORD"],
  CHIPMATE_SERVER_USERNAME: process.env["CHIPMATE_SERVER_USERNAME"],
  CHIPMATE_ENABLE_QUESTION_TOOL: truthy("CHIPMATE_ENABLE_QUESTION_TOOL"), // chipmate_change

  CHIPMATE_EXPERIMENTAL, // chipmate_change

  CHIPMATE_EXPERIMENTAL_FILEWATCHER: Config.boolean("CHIPMATE_EXPERIMENTAL_FILEWATCHER").pipe(Config.withDefault(false)), // chipmate_change

  CHIPMATE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("CHIPMATE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),

  CHIPMATE_EXPERIMENTAL_ICON_DISCOVERY: CHIPMATE_EXPERIMENTAL || truthy("CHIPMATE_EXPERIMENTAL_ICON_DISCOVERY"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("CHIPMATE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),

  CHIPMATE_ENABLE_EXA: truthy("CHIPMATE_ENABLE_EXA") || CHIPMATE_EXPERIMENTAL || truthy("CHIPMATE_EXPERIMENTAL_EXA"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("CHIPMATE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("CHIPMATE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_OXFMT: CHIPMATE_EXPERIMENTAL || truthy("CHIPMATE_EXPERIMENTAL_OXFMT"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_LSP_TY: truthy("CHIPMATE_EXPERIMENTAL_LSP_TY"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_LSP_TOOL: CHIPMATE_EXPERIMENTAL || truthy("CHIPMATE_EXPERIMENTAL_LSP_TOOL"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_PLAN_MODE: CHIPMATE_EXPERIMENTAL || truthy("CHIPMATE_EXPERIMENTAL_PLAN_MODE"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_SCOUT: CHIPMATE_EXPERIMENTAL || truthy("CHIPMATE_EXPERIMENTAL_SCOUT"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_MARKDOWN: !falsy("CHIPMATE_EXPERIMENTAL_MARKDOWN"), // chipmate_change

  CHIPMATE_ENABLE_PARALLEL: truthy("CHIPMATE_ENABLE_PARALLEL") || truthy("CHIPMATE_EXPERIMENTAL_PARALLEL"), // chipmate_change

  CHIPMATE_MODELS_URL: process.env["CHIPMATE_MODELS_URL"],

  CHIPMATE_MODELS_PATH: process.env["CHIPMATE_MODELS_PATH"],

  CHIPMATE_DISABLE_EMBEDDED_WEB_UI: truthy("CHIPMATE_DISABLE_EMBEDDED_WEB_UI"), // chipmate_change

  CHIPMATE_DB: process.env["CHIPMATE_DB"],

  CHIPMATE_DISABLE_CHANNEL_DB: truthy("CHIPMATE_DISABLE_CHANNEL_DB"), // chipmate_change

  CHIPMATE_SKIP_MIGRATIONS: truthy("CHIPMATE_SKIP_MIGRATIONS"), // chipmate_change

  CHIPMATE_STRICT_CONFIG_DEPS: truthy("CHIPMATE_STRICT_CONFIG_DEPS"), // chipmate_change

  CHIPMATE_WORKSPACE_ID: process.env["CHIPMATE_WORKSPACE_ID"],

  CHIPMATE_EXPERIMENTAL_WORKSPACES: enabledByExperimental("CHIPMATE_EXPERIMENTAL_WORKSPACES"),

  CHIPMATE_EXPERIMENTAL_EVENT_SYSTEM: CHIPMATE_EXPERIMENTAL || truthy("CHIPMATE_EXPERIMENTAL_EVENT_SYSTEM"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_SESSION_SWITCHING: CHIPMATE_EXPERIMENTAL || truthy("CHIPMATE_EXPERIMENTAL_SESSION_SWITCHING"), // chipmate_change

  CHIPMATE_EXPERIMENTAL_SESSION_SWITCHER: enabledByExperimental("CHIPMATE_EXPERIMENTAL_SESSION_SWITCHER"), // chipmate_change

  CHIPMATE_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("CHIPMATE_DISABLE_FFF"), // chipmate_change

  get CHIPMATE_DISABLE_PROJECT_CONFIG() {
    return truthy("CHIPMATE_DISABLE_PROJECT_CONFIG")
  },
  get CHIPMATE_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("CHIPMATE_EXPERIMENTAL_REFERENCES")
  },
  get CHIPMATE_TUI_CONFIG() {
    return process.env["CHIPMATE_TUI_CONFIG"]
  },
  get CHIPMATE_CONFIG_DIR() {
    return process.env["CHIPMATE_CONFIG_DIR"]
  },
  get CHIPMATE_PURE() {
    return truthy("CHIPMATE_PURE")
  },
  get CHIPMATE_PERMISSION() {
    return process.env["CHIPMATE_PERMISSION"]
  },
  get CHIPMATE_PLUGIN_META_FILE() {
    return process.env["CHIPMATE_PLUGIN_META_FILE"]
  },
  get CHIPMATE_CLIENT() {
    return process.env["CHIPMATE_CLIENT"] ?? "cli"
  },
  // chipmate_change start
  get CHIPMATE_SESSION_RETRY_LIMIT() {
    return number("CHIPMATE_SESSION_RETRY_LIMIT")
  },
  // chipmate_change end
}
